// <auto-generated />
namespace AmazonPupSpace.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class positiondatadeletedfromtheemployeeemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(positiondatadeletedfromtheemployeeemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202407271036367_position data deleted from the employeee model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
