// <auto-generated />
namespace AmazonPupSpace.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class employeeemailadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeeemailadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202408030120186_employee-email-add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
