// <auto-generated />
namespace AmazonPupSpace.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class employeeuserIDadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeeuserIDadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202408030244179_employee-userID-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
